"""
Complete NSE India Stock Universe
Covers: NIFTY 50, NIFTY Next 50, NIFTY Midcap 150, NIFTY Smallcap 250,
        NIFTY Microcap 250, and additional listed stocks — 1500+ symbols.

All symbols use the Yahoo Finance .NS suffix for NSE India.
"""

NSE_STOCKS = [
    # ═══════════════════════════════════════════════════════
    # NIFTY 50
    # ═══════════════════════════════════════════════════════
    {"symbol":"RELIANCE.NS","name":"Reliance Industries","sector":"Energy","index":"NIFTY 50"},
    {"symbol":"TCS.NS","name":"Tata Consultancy Services","sector":"IT","index":"NIFTY 50"},
    {"symbol":"HDFCBANK.NS","name":"HDFC Bank","sector":"Banking","index":"NIFTY 50"},
    {"symbol":"ICICIBANK.NS","name":"ICICI Bank","sector":"Banking","index":"NIFTY 50"},
    {"symbol":"INFY.NS","name":"Infosys","sector":"IT","index":"NIFTY 50"},
    {"symbol":"HINDUNILVR.NS","name":"Hindustan Unilever","sector":"FMCG","index":"NIFTY 50"},
    {"symbol":"ITC.NS","name":"ITC Limited","sector":"FMCG","index":"NIFTY 50"},
    {"symbol":"SBIN.NS","name":"State Bank of India","sector":"Banking","index":"NIFTY 50"},
    {"symbol":"BHARTIARTL.NS","name":"Bharti Airtel","sector":"Telecom","index":"NIFTY 50"},
    {"symbol":"KOTAKBANK.NS","name":"Kotak Mahindra Bank","sector":"Banking","index":"NIFTY 50"},
    {"symbol":"LT.NS","name":"Larsen & Toubro","sector":"Infra","index":"NIFTY 50"},
    {"symbol":"AXISBANK.NS","name":"Axis Bank","sector":"Banking","index":"NIFTY 50"},
    {"symbol":"ASIANPAINT.NS","name":"Asian Paints","sector":"Chemicals","index":"NIFTY 50"},
    {"symbol":"MARUTI.NS","name":"Maruti Suzuki","sector":"Auto","index":"NIFTY 50"},
    {"symbol":"SUNPHARMA.NS","name":"Sun Pharmaceutical","sector":"Pharma","index":"NIFTY 50"},
    {"symbol":"TITAN.NS","name":"Titan Company","sector":"Consumer","index":"NIFTY 50"},
    {"symbol":"BAJFINANCE.NS","name":"Bajaj Finance","sector":"NBFC","index":"NIFTY 50"},
    {"symbol":"WIPRO.NS","name":"Wipro","sector":"IT","index":"NIFTY 50"},
    {"symbol":"NESTLEIND.NS","name":"Nestle India","sector":"FMCG","index":"NIFTY 50"},
    {"symbol":"ULTRACEMCO.NS","name":"UltraTech Cement","sector":"Cement","index":"NIFTY 50"},
    {"symbol":"TATAMOTORS.NS","name":"Tata Motors","sector":"Auto","index":"NIFTY 50"},
    {"symbol":"POWERGRID.NS","name":"Power Grid Corporation","sector":"Power","index":"NIFTY 50"},
    {"symbol":"NTPC.NS","name":"NTPC Limited","sector":"Power","index":"NIFTY 50"},
    {"symbol":"ONGC.NS","name":"Oil & Natural Gas Corp","sector":"Energy","index":"NIFTY 50"},
    {"symbol":"HCLTECH.NS","name":"HCL Technologies","sector":"IT","index":"NIFTY 50"},
    {"symbol":"TATASTEEL.NS","name":"Tata Steel","sector":"Metals","index":"NIFTY 50"},
    {"symbol":"BAJAJFINSV.NS","name":"Bajaj Finserv","sector":"NBFC","index":"NIFTY 50"},
    {"symbol":"TECHM.NS","name":"Tech Mahindra","sector":"IT","index":"NIFTY 50"},
    {"symbol":"GRASIM.NS","name":"Grasim Industries","sector":"Diversified","index":"NIFTY 50"},
    {"symbol":"ADANIPORTS.NS","name":"Adani Ports & SEZ","sector":"Logistics","index":"NIFTY 50"},
    {"symbol":"COALINDIA.NS","name":"Coal India","sector":"Mining","index":"NIFTY 50"},
    {"symbol":"DRREDDY.NS","name":"Dr. Reddy's Laboratories","sector":"Pharma","index":"NIFTY 50"},
    {"symbol":"JSWSTEEL.NS","name":"JSW Steel","sector":"Metals","index":"NIFTY 50"},
    {"symbol":"M&M.NS","name":"Mahindra & Mahindra","sector":"Auto","index":"NIFTY 50"},
    {"symbol":"EICHERMOT.NS","name":"Eicher Motors","sector":"Auto","index":"NIFTY 50"},
    {"symbol":"BPCL.NS","name":"Bharat Petroleum Corp","sector":"Energy","index":"NIFTY 50"},
    {"symbol":"INDUSINDBK.NS","name":"IndusInd Bank","sector":"Banking","index":"NIFTY 50"},
    {"symbol":"CIPLA.NS","name":"Cipla","sector":"Pharma","index":"NIFTY 50"},
    {"symbol":"TATACONSUM.NS","name":"Tata Consumer Products","sector":"FMCG","index":"NIFTY 50"},
    {"symbol":"APOLLOHOSP.NS","name":"Apollo Hospitals","sector":"Healthcare","index":"NIFTY 50"},
    {"symbol":"HINDALCO.NS","name":"Hindalco Industries","sector":"Metals","index":"NIFTY 50"},
    {"symbol":"HEROMOTOCO.NS","name":"Hero MotoCorp","sector":"Auto","index":"NIFTY 50"},
    {"symbol":"SHRIRAMFIN.NS","name":"Shriram Finance","sector":"NBFC","index":"NIFTY 50"},
    {"symbol":"SBILIFE.NS","name":"SBI Life Insurance","sector":"Insurance","index":"NIFTY 50"},
    {"symbol":"HDFCLIFE.NS","name":"HDFC Life Insurance","sector":"Insurance","index":"NIFTY 50"},
    {"symbol":"BRITANNIA.NS","name":"Britannia Industries","sector":"FMCG","index":"NIFTY 50"},
    {"symbol":"DIVISLAB.NS","name":"Divi's Laboratories","sector":"Pharma","index":"NIFTY 50"},
    {"symbol":"TRENT.NS","name":"Trent Limited","sector":"Retail","index":"NIFTY 50"},
    {"symbol":"BEL.NS","name":"Bharat Electronics","sector":"Defence","index":"NIFTY 50"},
    {"symbol":"BAJAJ-AUTO.NS","name":"Bajaj Auto","sector":"Auto","index":"NIFTY 50"},

    # ═══════════════════════════════════════════════════════
    # NIFTY NEXT 50
    # ═══════════════════════════════════════════════════════
    {"symbol":"ADANIENT.NS","name":"Adani Enterprises","sector":"Diversified","index":"NIFTY Next 50"},
    {"symbol":"ADANIGREEN.NS","name":"Adani Green Energy","sector":"Power","index":"NIFTY Next 50"},
    {"symbol":"ADANIPOWER.NS","name":"Adani Power","sector":"Power","index":"NIFTY Next 50"},
    {"symbol":"ADANITRANS.NS","name":"Adani Transmission","sector":"Power","index":"NIFTY Next 50"},
    {"symbol":"SIEMENS.NS","name":"Siemens India","sector":"Capital Goods","index":"NIFTY Next 50"},
    {"symbol":"HAVELLS.NS","name":"Havells India","sector":"Capital Goods","index":"NIFTY Next 50"},
    {"symbol":"PIDILITIND.NS","name":"Pidilite Industries","sector":"Chemicals","index":"NIFTY Next 50"},
    {"symbol":"DLF.NS","name":"DLF Limited","sector":"Real Estate","index":"NIFTY Next 50"},
    {"symbol":"GODREJCP.NS","name":"Godrej Consumer Products","sector":"FMCG","index":"NIFTY Next 50"},
    {"symbol":"DABUR.NS","name":"Dabur India","sector":"FMCG","index":"NIFTY Next 50"},
    {"symbol":"MARICO.NS","name":"Marico","sector":"FMCG","index":"NIFTY Next 50"},
    {"symbol":"MUTHOOTFIN.NS","name":"Muthoot Finance","sector":"NBFC","index":"NIFTY Next 50"},
    {"symbol":"IRCTC.NS","name":"Indian Railway Catering","sector":"Travel","index":"NIFTY Next 50"},
    {"symbol":"IRFC.NS","name":"Indian Railway Finance","sector":"NBFC","index":"NIFTY Next 50"},
    {"symbol":"HAL.NS","name":"Hindustan Aeronautics","sector":"Defence","index":"NIFTY Next 50"},
    {"symbol":"SAIL.NS","name":"Steel Authority of India","sector":"Metals","index":"NIFTY Next 50"},
    {"symbol":"NMDC.NS","name":"NMDC Limited","sector":"Mining","index":"NIFTY Next 50"},
    {"symbol":"HINDPETRO.NS","name":"Hindustan Petroleum","sector":"Energy","index":"NIFTY Next 50"},
    {"symbol":"IOC.NS","name":"Indian Oil Corporation","sector":"Energy","index":"NIFTY Next 50"},
    {"symbol":"GAIL.NS","name":"GAIL India","sector":"Energy","index":"NIFTY Next 50"},
    {"symbol":"PETRONET.NS","name":"Petronet LNG","sector":"Energy","index":"NIFTY Next 50"},
    {"symbol":"ZOMATO.NS","name":"Zomato","sector":"Internet","index":"NIFTY Next 50"},
    {"symbol":"PAYTM.NS","name":"Paytm (One97 Comm)","sector":"Fintech","index":"NIFTY Next 50"},
    {"symbol":"NYKAA.NS","name":"Nykaa (FSN E-Commerce)","sector":"E-Commerce","index":"NIFTY Next 50"},
    {"symbol":"POLICYBZR.NS","name":"PB Fintech (PolicyBazaar)","sector":"Fintech","index":"NIFTY Next 50"},
    {"symbol":"BANKBARODA.NS","name":"Bank of Baroda","sector":"Banking","index":"NIFTY Next 50"},
    {"symbol":"PNB.NS","name":"Punjab National Bank","sector":"Banking","index":"NIFTY Next 50"},
    {"symbol":"CANBK.NS","name":"Canara Bank","sector":"Banking","index":"NIFTY Next 50"},
    {"symbol":"UNIONBANK.NS","name":"Union Bank of India","sector":"Banking","index":"NIFTY Next 50"},
    {"symbol":"RECLTD.NS","name":"REC Limited","sector":"NBFC","index":"NIFTY Next 50"},
    {"symbol":"PFC.NS","name":"Power Finance Corporation","sector":"NBFC","index":"NIFTY Next 50"},
    {"symbol":"CONCOR.NS","name":"Container Corporation","sector":"Logistics","index":"NIFTY Next 50"},
    {"symbol":"GODREJPROP.NS","name":"Godrej Properties","sector":"Real Estate","index":"NIFTY Next 50"},
    {"symbol":"INDUSTOWER.NS","name":"Indus Towers","sector":"Telecom","index":"NIFTY Next 50"},
    {"symbol":"VEDL.NS","name":"Vedanta","sector":"Metals","index":"NIFTY Next 50"},
    {"symbol":"ICICIPRULI.NS","name":"ICICI Prudential Life","sector":"Insurance","index":"NIFTY Next 50"},
    {"symbol":"ICICIGI.NS","name":"ICICI Lombard General","sector":"Insurance","index":"NIFTY Next 50"},
    {"symbol":"SBICARD.NS","name":"SBI Cards","sector":"NBFC","index":"NIFTY Next 50"},
    {"symbol":"CHOLAFIN.NS","name":"Cholamandalam Investment","sector":"NBFC","index":"NIFTY Next 50"},
    {"symbol":"PNBHOUSING.NS","name":"PNB Housing Finance","sector":"NBFC","index":"NIFTY Next 50"},

    # ═══════════════════════════════════════════════════════
    # NIFTY MIDCAP 150
    # ═══════════════════════════════════════════════════════
    {"symbol":"PERSISTENT.NS","name":"Persistent Systems","sector":"IT","index":"NIFTY Midcap"},
    {"symbol":"COFORGE.NS","name":"Coforge","sector":"IT","index":"NIFTY Midcap"},
    {"symbol":"LTIM.NS","name":"LTIMindtree","sector":"IT","index":"NIFTY Midcap"},
    {"symbol":"MPHASIS.NS","name":"Mphasis","sector":"IT","index":"NIFTY Midcap"},
    {"symbol":"KPITTECH.NS","name":"KPIT Technologies","sector":"IT","index":"NIFTY Midcap"},
    {"symbol":"OFSS.NS","name":"Oracle Financial Services","sector":"IT","index":"NIFTY Midcap"},
    {"symbol":"BSOFT.NS","name":"Birlasoft","sector":"IT","index":"NIFTY Midcap"},
    {"symbol":"TANLA.NS","name":"Tanla Platforms","sector":"IT","index":"NIFTY Midcap"},
    {"symbol":"MASTEK.NS","name":"Mastek","sector":"IT","index":"NIFTY Midcap"},
    {"symbol":"ROUTE.NS","name":"Route Mobile","sector":"IT","index":"NIFTY Midcap"},
    {"symbol":"NAUKRI.NS","name":"Info Edge India","sector":"Internet","index":"NIFTY Midcap"},
    {"symbol":"ZYDUSLIFE.NS","name":"Zydus Lifesciences","sector":"Pharma","index":"NIFTY Midcap"},
    {"symbol":"TORNTPHARM.NS","name":"Torrent Pharmaceuticals","sector":"Pharma","index":"NIFTY Midcap"},
    {"symbol":"AUROPHARMA.NS","name":"Aurobindo Pharma","sector":"Pharma","index":"NIFTY Midcap"},
    {"symbol":"LUPIN.NS","name":"Lupin","sector":"Pharma","index":"NIFTY Midcap"},
    {"symbol":"BIOCON.NS","name":"Biocon","sector":"Pharma","index":"NIFTY Midcap"},
    {"symbol":"ALKEM.NS","name":"Alkem Laboratories","sector":"Pharma","index":"NIFTY Midcap"},
    {"symbol":"AJANTPHARM.NS","name":"Ajanta Pharma","sector":"Pharma","index":"NIFTY Midcap"},
    {"symbol":"GRANULES.NS","name":"Granules India","sector":"Pharma","index":"NIFTY Midcap"},
    {"symbol":"NATCOPHARM.NS","name":"Natco Pharma","sector":"Pharma","index":"NIFTY Midcap"},
    {"symbol":"LALPATHLAB.NS","name":"Dr. Lal PathLabs","sector":"Healthcare","index":"NIFTY Midcap"},
    {"symbol":"METROPOLIS.NS","name":"Metropolis Healthcare","sector":"Healthcare","index":"NIFTY Midcap"},
    {"symbol":"MAXHEALTH.NS","name":"Max Healthcare","sector":"Healthcare","index":"NIFTY Midcap"},
    {"symbol":"FORTIS.NS","name":"Fortis Healthcare","sector":"Healthcare","index":"NIFTY Midcap"},
    {"symbol":"NH.NS","name":"Narayana Hrudayalaya","sector":"Healthcare","index":"NIFTY Midcap"},
    {"symbol":"AARTIIND.NS","name":"Aarti Industries","sector":"Chemicals","index":"NIFTY Midcap"},
    {"symbol":"DEEPAKNITRITE.NS","name":"Deepak Nitrite","sector":"Chemicals","index":"NIFTY Midcap"},
    {"symbol":"CLEAN.NS","name":"Clean Science & Technology","sector":"Chemicals","index":"NIFTY Midcap"},
    {"symbol":"NAVINFLUOR.NS","name":"Navin Fluorine","sector":"Chemicals","index":"NIFTY Midcap"},
    {"symbol":"FINEORG.NS","name":"Fine Organic Industries","sector":"Chemicals","index":"NIFTY Midcap"},
    {"symbol":"SRF.NS","name":"SRF Limited","sector":"Chemicals","index":"NIFTY Midcap"},
    {"symbol":"ATUL.NS","name":"Atul Limited","sector":"Chemicals","index":"NIFTY Midcap"},
    {"symbol":"TATACHEM.NS","name":"Tata Chemicals","sector":"Chemicals","index":"NIFTY Midcap"},
    {"symbol":"CHAMBLFERT.NS","name":"Chambal Fertilisers","sector":"Fertilisers","index":"NIFTY Midcap"},
    {"symbol":"COROMANDEL.NS","name":"Coromandel International","sector":"Fertilisers","index":"NIFTY Midcap"},
    {"symbol":"GNFC.NS","name":"GNFC","sector":"Fertilisers","index":"NIFTY Midcap"},
    {"symbol":"TATAPOWER.NS","name":"Tata Power","sector":"Power","index":"NIFTY Midcap"},
    {"symbol":"SUZLON.NS","name":"Suzlon Energy","sector":"Power","index":"NIFTY Midcap"},
    {"symbol":"NHPC.NS","name":"NHPC Limited","sector":"Power","index":"NIFTY Midcap"},
    {"symbol":"JSWENERGY.NS","name":"JSW Energy","sector":"Power","index":"NIFTY Midcap"},
    {"symbol":"TORNTPOWER.NS","name":"Torrent Power","sector":"Power","index":"NIFTY Midcap"},
    {"symbol":"CESC.NS","name":"CESC Limited","sector":"Power","index":"NIFTY Midcap"},
    {"symbol":"SJVN.NS","name":"SJVN Limited","sector":"Power","index":"NIFTY Midcap"},
    {"symbol":"INDIGO.NS","name":"InterGlobe Aviation","sector":"Aviation","index":"NIFTY Midcap"},
    {"symbol":"MRF.NS","name":"MRF","sector":"Auto Ancillary","index":"NIFTY Midcap"},
    {"symbol":"TVSMOTOR.NS","name":"TVS Motor Company","sector":"Auto","index":"NIFTY Midcap"},
    {"symbol":"ASHOKLEY.NS","name":"Ashok Leyland","sector":"Auto","index":"NIFTY Midcap"},
    {"symbol":"ESCORTS.NS","name":"Escorts Kubota","sector":"Auto","index":"NIFTY Midcap"},
    {"symbol":"BALKRISIND.NS","name":"Balkrishna Industries","sector":"Auto Ancillary","index":"NIFTY Midcap"},
    {"symbol":"APOLLOTYRE.NS","name":"Apollo Tyres","sector":"Auto Ancillary","index":"NIFTY Midcap"},
    {"symbol":"MOTHERSON.NS","name":"Samvardhana Motherson","sector":"Auto Ancillary","index":"NIFTY Midcap"},
    {"symbol":"FEDERALBNK.NS","name":"Federal Bank","sector":"Banking","index":"NIFTY Midcap"},
    {"symbol":"IDFCFIRSTB.NS","name":"IDFC First Bank","sector":"Banking","index":"NIFTY Midcap"},
    {"symbol":"BANDHANBNK.NS","name":"Bandhan Bank","sector":"Banking","index":"NIFTY Midcap"},
    {"symbol":"RBLBANK.NS","name":"RBL Bank","sector":"Banking","index":"NIFTY Midcap"},
    {"symbol":"KARURVYSYA.NS","name":"Karur Vysya Bank","sector":"Banking","index":"NIFTY Midcap"},
    {"symbol":"DCBBANK.NS","name":"DCB Bank","sector":"Banking","index":"NIFTY Midcap"},
    {"symbol":"SOUTHBANK.NS","name":"South Indian Bank","sector":"Banking","index":"NIFTY Midcap"},
    {"symbol":"KTKBANK.NS","name":"Karnataka Bank","sector":"Banking","index":"NIFTY Midcap"},
    {"symbol":"M&MFIN.NS","name":"M&M Financial Services","sector":"NBFC","index":"NIFTY Midcap"},
    {"symbol":"LICHSGFIN.NS","name":"LIC Housing Finance","sector":"NBFC","index":"NIFTY Midcap"},
    {"symbol":"MANAPPURAM.NS","name":"Manappuram Finance","sector":"NBFC","index":"NIFTY Midcap"},
    {"symbol":"ABCAPITAL.NS","name":"Aditya Birla Capital","sector":"NBFC","index":"NIFTY Midcap"},
    {"symbol":"PRESTIGE.NS","name":"Prestige Estates","sector":"Real Estate","index":"NIFTY Midcap"},
    {"symbol":"OBEROIRLTY.NS","name":"Oberoi Realty","sector":"Real Estate","index":"NIFTY Midcap"},
    {"symbol":"PHOENIXLTD.NS","name":"The Phoenix Mills","sector":"Real Estate","index":"NIFTY Midcap"},
    {"symbol":"SOBHA.NS","name":"Sobha Limited","sector":"Real Estate","index":"NIFTY Midcap"},
    {"symbol":"BRIGADE.NS","name":"Brigade Enterprises","sector":"Real Estate","index":"NIFTY Midcap"},
    {"symbol":"DMART.NS","name":"Avenue Supermarts (D-Mart)","sector":"Retail","index":"NIFTY Midcap"},
    {"symbol":"ABFRL.NS","name":"Aditya Birla Fashion","sector":"Retail","index":"NIFTY Midcap"},
    {"symbol":"JUBLFOOD.NS","name":"Jubilant FoodWorks","sector":"QSR","index":"NIFTY Midcap"},
    {"symbol":"DEVYANI.NS","name":"Devyani International","sector":"QSR","index":"NIFTY Midcap"},
    {"symbol":"WESTLIFE.NS","name":"Westlife Foodworld","sector":"QSR","index":"NIFTY Midcap"},
    {"symbol":"COLPAL.NS","name":"Colgate-Palmolive India","sector":"FMCG","index":"NIFTY Midcap"},
    {"symbol":"EMAMILTD.NS","name":"Emami","sector":"FMCG","index":"NIFTY Midcap"},
    {"symbol":"JYOTHYLAB.NS","name":"Jyothy Labs","sector":"FMCG","index":"NIFTY Midcap"},
    {"symbol":"BATAINDIA.NS","name":"Bata India","sector":"Consumer","index":"NIFTY Midcap"},
    {"symbol":"PAGEIND.NS","name":"Page Industries","sector":"Consumer","index":"NIFTY Midcap"},
    {"symbol":"DIXON.NS","name":"Dixon Technologies","sector":"Electronics","index":"NIFTY Midcap"},
    {"symbol":"AMBER.NS","name":"Amber Enterprises","sector":"Electronics","index":"NIFTY Midcap"},
    {"symbol":"KAYNES.NS","name":"Kaynes Technology","sector":"Electronics","index":"NIFTY Midcap"},
    {"symbol":"APLAPOLLO.NS","name":"APL Apollo Tubes","sector":"Steel","index":"NIFTY Midcap"},
    {"symbol":"JKCEMENT.NS","name":"JK Cement","sector":"Cement","index":"NIFTY Midcap"},
    {"symbol":"DALBHARAT.NS","name":"Dalmia Bharat","sector":"Cement","index":"NIFTY Midcap"},
    {"symbol":"SHREECEM.NS","name":"Shree Cement","sector":"Cement","index":"NIFTY Midcap"},
    {"symbol":"GMRINFRA.NS","name":"GMR Airports Infra","sector":"Infra","index":"NIFTY Midcap"},
    {"symbol":"CUMMINSIND.NS","name":"Cummins India","sector":"Capital Goods","index":"NIFTY Midcap"},
    {"symbol":"VOLTAS.NS","name":"Voltas","sector":"Capital Goods","index":"NIFTY Midcap"},
    {"symbol":"CROMPTON.NS","name":"Crompton Greaves Consumer","sector":"Consumer Durables","index":"NIFTY Midcap"},
    {"symbol":"BLUESTARCO.NS","name":"Blue Star","sector":"Consumer Durables","index":"NIFTY Midcap"},
    {"symbol":"MAPMYINDIA.NS","name":"C.E. Info Systems","sector":"Technology","index":"NIFTY Midcap"},

    # ═══════════════════════════════════════════════════════
    # NIFTY SMALLCAP 250
    # ═══════════════════════════════════════════════════════
    {"symbol":"IONEXCHANG.NS","name":"Ion Exchange","sector":"Water","index":"NIFTY Smallcap"},
    {"symbol":"RAILTEL.NS","name":"RailTel Corporation","sector":"IT","index":"NIFTY Smallcap"},
    {"symbol":"IREDA.NS","name":"IREDA","sector":"NBFC","index":"NIFTY Smallcap"},
    {"symbol":"RVNL.NS","name":"Rail Vikas Nigam","sector":"Infra","index":"NIFTY Smallcap"},
    {"symbol":"BEML.NS","name":"BEML Limited","sector":"Defence","index":"NIFTY Smallcap"},
    {"symbol":"BDL.NS","name":"Bharat Dynamics","sector":"Defence","index":"NIFTY Smallcap"},
    {"symbol":"DATAPATTNS.NS","name":"Data Patterns India","sector":"Defence","index":"NIFTY Smallcap"},
    {"symbol":"PARAS.NS","name":"Paras Defence","sector":"Defence","index":"NIFTY Smallcap"},
    {"symbol":"MTAR.NS","name":"MTAR Technologies","sector":"Defence","index":"NIFTY Smallcap"},
    {"symbol":"IDEAFORGE.NS","name":"ideaForge Technology","sector":"Defence","index":"NIFTY Smallcap"},
    {"symbol":"COCHINSHIP.NS","name":"Cochin Shipyard","sector":"Defence","index":"NIFTY Smallcap"},
    {"symbol":"MIDHANI.NS","name":"Mishra Dhatu Nigam","sector":"Defence","index":"NIFTY Smallcap"},
    {"symbol":"GARFIBRES.NS","name":"Garden Reach Shipbuilders","sector":"Defence","index":"NIFTY Smallcap"},
    {"symbol":"GRINDWELL.NS","name":"Grindwell Norton","sector":"Capital Goods","index":"NIFTY Smallcap"},
    {"symbol":"GRAPHITE.NS","name":"Graphite India","sector":"Capital Goods","index":"NIFTY Smallcap"},
    {"symbol":"ELGIEQUIP.NS","name":"Elgi Equipments","sector":"Capital Goods","index":"NIFTY Smallcap"},
    {"symbol":"THERMAX.NS","name":"Thermax","sector":"Capital Goods","index":"NIFTY Smallcap"},
    {"symbol":"KALPATPOWR.NS","name":"KalpatPower","sector":"Capital Goods","index":"NIFTY Smallcap"},
    {"symbol":"KEC.NS","name":"KEC International","sector":"Capital Goods","index":"NIFTY Smallcap"},
    {"symbol":"AIAENG.NS","name":"AIA Engineering","sector":"Capital Goods","index":"NIFTY Smallcap"},
    {"symbol":"CRAFTSMAN.NS","name":"Craftsman Automation","sector":"Auto Ancillary","index":"NIFTY Smallcap"},
    {"symbol":"SUPRAJIT.NS","name":"Suprajit Engineering","sector":"Auto Ancillary","index":"NIFTY Smallcap"},
    {"symbol":"ENDURANCE.NS","name":"Endurance Technologies","sector":"Auto Ancillary","index":"NIFTY Smallcap"},
    {"symbol":"SANSERA.NS","name":"Sansera Engineering","sector":"Auto Ancillary","index":"NIFTY Smallcap"},
    {"symbol":"GABRIEL.NS","name":"Gabriel India","sector":"Auto Ancillary","index":"NIFTY Smallcap"},
    {"symbol":"MINDAIND.NS","name":"Minda Industries","sector":"Auto Ancillary","index":"NIFTY Smallcap"},
    {"symbol":"SUBROS.NS","name":"Subros Limited","sector":"Auto Ancillary","index":"NIFTY Smallcap"},
    {"symbol":"WABCO.NS","name":"ZF Commercial Vehicle","sector":"Auto Ancillary","index":"NIFTY Smallcap"},
    {"symbol":"AUTOAXLES.NS","name":"Automotive Axles","sector":"Auto Ancillary","index":"NIFTY Smallcap"},
    {"symbol":"SUNDRMFAST.NS","name":"Sundram Fasteners","sector":"Auto Ancillary","index":"NIFTY Smallcap"},
    {"symbol":"MAHINDCIE.NS","name":"Mahindra CIE","sector":"Auto Ancillary","index":"NIFTY Smallcap"},
    {"symbol":"TIINDIA.NS","name":"Tube Investments India","sector":"Auto Ancillary","index":"NIFTY Smallcap"},
    {"symbol":"VARROC.NS","name":"Varroc Engineering","sector":"Auto Ancillary","index":"NIFTY Smallcap"},
    {"symbol":"EXIDEIND.NS","name":"Exide Industries","sector":"Auto Ancillary","index":"NIFTY Smallcap"},
    {"symbol":"AMARAJABAT.NS","name":"Amara Raja Energy","sector":"Auto Ancillary","index":"NIFTY Smallcap"},
    {"symbol":"BOSCHLTD.NS","name":"Bosch India","sector":"Auto Ancillary","index":"NIFTY Smallcap"},
    {"symbol":"SUNDRESIND.NS","name":"Sundram Fasteners","sector":"Auto Ancillary","index":"NIFTY Smallcap"},
    {"symbol":"ZFSTERLITE.NS","name":"ZF Steering Gear","sector":"Auto Ancillary","index":"NIFTY Smallcap"},
    {"symbol":"JBMA.NS","name":"JBM Auto","sector":"Auto Ancillary","index":"NIFTY Smallcap"},
    {"symbol":"FIEM.NS","name":"Fiem Industries","sector":"Auto Ancillary","index":"NIFTY Smallcap"},
    {"symbol":"SPANDANA.NS","name":"Spandana Sphoorty","sector":"NBFC","index":"NIFTY Smallcap"},
    {"symbol":"CREDITACC.NS","name":"CreditAccess Grameen","sector":"NBFC","index":"NIFTY Smallcap"},
    {"symbol":"UJJIVAN.NS","name":"Ujjivan Financial","sector":"NBFC","index":"NIFTY Smallcap"},
    {"symbol":"UJJIVANSFB.NS","name":"Ujjivan Small Finance Bank","sector":"Banking","index":"NIFTY Smallcap"},
    {"symbol":"EQUITASBNK.NS","name":"Equitas Small Finance Bank","sector":"Banking","index":"NIFTY Smallcap"},
    {"symbol":"SURYODAY.NS","name":"Suryoday Small Finance","sector":"Banking","index":"NIFTY Smallcap"},
    {"symbol":"AUBANK.NS","name":"AU Small Finance Bank","sector":"Banking","index":"NIFTY Smallcap"},
    {"symbol":"ESAFSFB.NS","name":"ESAF Small Finance Bank","sector":"Banking","index":"NIFTY Smallcap"},
    {"symbol":"JANA.NS","name":"Jana Small Finance Bank","sector":"Banking","index":"NIFTY Smallcap"},
    {"symbol":"HDFCAMC.NS","name":"HDFC AMC","sector":"AMC","index":"NIFTY Smallcap"},
    {"symbol":"ABSLAMC.NS","name":"Aditya Birla Sun Life AMC","sector":"AMC","index":"NIFTY Smallcap"},
    {"symbol":"NIPPONLIFE.NS","name":"Nippon Life India AMC","sector":"AMC","index":"NIFTY Smallcap"},
    {"symbol":"UTIAMC.NS","name":"UTI AMC","sector":"AMC","index":"NIFTY Smallcap"},
    {"symbol":"360ONE.NS","name":"360 ONE WAM","sector":"Wealth Mgmt","index":"NIFTY Smallcap"},
    {"symbol":"IIFL.NS","name":"IIFL Finance","sector":"NBFC","index":"NIFTY Smallcap"},
    {"symbol":"IIFLSEC.NS","name":"IIFL Securities","sector":"NBFC","index":"NIFTY Smallcap"},
    {"symbol":"ANGELONE.NS","name":"Angel One","sector":"Broking","index":"NIFTY Smallcap"},
    {"symbol":"MCXINDIA.NS","name":"Multi Commodity Exchange","sector":"Exchange","index":"NIFTY Smallcap"},
    {"symbol":"BSEINDIA.NS","name":"BSE Limited","sector":"Exchange","index":"NIFTY Smallcap"},
    {"symbol":"CDSL.NS","name":"CDSL","sector":"Exchange","index":"NIFTY Smallcap"},
    {"symbol":"CAMS.NS","name":"Computer Age Mgmt Services","sector":"Financial Services","index":"NIFTY Smallcap"},
    {"symbol":"KALYANKJIL.NS","name":"Kalyan Jewellers","sector":"Consumer","index":"NIFTY Smallcap"},
    {"symbol":"SENCO.NS","name":"Senco Gold","sector":"Consumer","index":"NIFTY Smallcap"},
    {"symbol":"THANGAMAYL.NS","name":"Thangamayil Jewellery","sector":"Consumer","index":"NIFTY Smallcap"},
    {"symbol":"RAJESHEXPO.NS","name":"Rajesh Exports","sector":"Consumer","index":"NIFTY Smallcap"},
    {"symbol":"PCJEWELLER.NS","name":"PC Jeweller","sector":"Consumer","index":"NIFTY Smallcap"},
    {"symbol":"VIPIND.NS","name":"VIP Industries","sector":"Consumer","index":"NIFTY Smallcap"},
    {"symbol":"RELAXO.NS","name":"Relaxo Footwears","sector":"Consumer","index":"NIFTY Smallcap"},
    {"symbol":"RAYMOND.NS","name":"Raymond","sector":"Textiles","index":"NIFTY Smallcap"},
    {"symbol":"KPRMILL.NS","name":"K.P.R. Mill","sector":"Textiles","index":"NIFTY Smallcap"},
    {"symbol":"WELSPUNIND.NS","name":"Welspun India","sector":"Textiles","index":"NIFTY Smallcap"},
    {"symbol":"TRIDENT.NS","name":"Trident Limited","sector":"Textiles","index":"NIFTY Smallcap"},
    {"symbol":"VARDHMAN.NS","name":"Vardhman Textiles","sector":"Textiles","index":"NIFTY Smallcap"},
    {"symbol":"ARVIND.NS","name":"Arvind Limited","sector":"Textiles","index":"NIFTY Smallcap"},
    {"symbol":"SPORTKING.NS","name":"Sportking India","sector":"Textiles","index":"NIFTY Smallcap"},
    {"symbol":"NITIRAJ.NS","name":"Nitiraj Engineers","sector":"Textiles","index":"NIFTY Smallcap"},
    {"symbol":"INDHOTEL.NS","name":"Indian Hotels (Taj)","sector":"Hospitality","index":"NIFTY Smallcap"},
    {"symbol":"LEMONTRE.NS","name":"Lemon Tree Hotels","sector":"Hospitality","index":"NIFTY Smallcap"},
    {"symbol":"CHALET.NS","name":"Chalet Hotels","sector":"Hospitality","index":"NIFTY Smallcap"},
    {"symbol":"MAHLOG.NS","name":"Mahindra Logistics","sector":"Logistics","index":"NIFTY Smallcap"},
    {"symbol":"DELHIVERY.NS","name":"Delhivery","sector":"Logistics","index":"NIFTY Smallcap"},
    {"symbol":"BLUEDART.NS","name":"Blue Dart Express","sector":"Logistics","index":"NIFTY Smallcap"},
    {"symbol":"TCI.NS","name":"Transport Corporation","sector":"Logistics","index":"NIFTY Smallcap"},
    {"symbol":"GESHIP.NS","name":"Great Eastern Shipping","sector":"Logistics","index":"NIFTY Smallcap"},
    {"symbol":"SCI.NS","name":"Shipping Corporation","sector":"Logistics","index":"NIFTY Smallcap"},
    {"symbol":"CARTRADE.NS","name":"CarTrade Tech","sector":"Internet","index":"NIFTY Smallcap"},
    {"symbol":"EASEMYTRIP.NS","name":"Easy Trip Planners","sector":"Travel","index":"NIFTY Smallcap"},

    # ═══════════════════════════════════════════════════════
    # NIFTY MICROCAP / OTHER LISTED
    # ═══════════════════════════════════════════════════════
    {"symbol":"APTUS.NS","name":"Aptus Value Housing Finance","sector":"NBFC","index":"NIFTY Microcap"},
    {"symbol":"HOMEFIRST.NS","name":"Home First Finance","sector":"NBFC","index":"NIFTY Microcap"},
    {"symbol":"AAVAS.NS","name":"Aavas Financiers","sector":"NBFC","index":"NIFTY Microcap"},
    {"symbol":"REPCO.NS","name":"Repco Home Finance","sector":"NBFC","index":"NIFTY Microcap"},
    {"symbol":"CANFINHOME.NS","name":"Can Fin Homes","sector":"NBFC","index":"NIFTY Microcap"},
    {"symbol":"GRUH.NS","name":"Gruh Finance","sector":"NBFC","index":"NIFTY Microcap"},
    {"symbol":"KOTAKBANK.NS","name":"Kotak Mahindra Bank","sector":"Banking","index":"NIFTY Microcap"},
    {"symbol":"STARHEALTH.NS","name":"Star Health Insurance","sector":"Insurance","index":"NIFTY Microcap"},
    {"symbol":"GODIGIT.NS","name":"Go Digit General Insurance","sector":"Insurance","index":"NIFTY Microcap"},
    {"symbol":"NIACL.NS","name":"New India Assurance","sector":"Insurance","index":"NIFTY Microcap"},
    {"symbol":"GICRE.NS","name":"GIC Re","sector":"Insurance","index":"NIFTY Microcap"},
    {"symbol":"LICI.NS","name":"LIC of India","sector":"Insurance","index":"NIFTY Microcap"},
    {"symbol":"AETHER.NS","name":"Aether Industries","sector":"Chemicals","index":"NIFTY Microcap"},
    {"symbol":"PCBL.NS","name":"PCBL Limited","sector":"Chemicals","index":"NIFTY Microcap"},
    {"symbol":"TRONOX.NS","name":"Kronox Lab Sciences","sector":"Chemicals","index":"NIFTY Microcap"},
    {"symbol":"VINDHYATEL.NS","name":"Vindhya Telelinks","sector":"Telecom","index":"NIFTY Microcap"},
    {"symbol":"HFCL.NS","name":"HFCL Limited","sector":"Telecom","index":"NIFTY Microcap"},
    {"symbol":"STLTECH.NS","name":"Sterlite Technologies","sector":"Telecom","index":"NIFTY Microcap"},
    {"symbol":"TTML.NS","name":"Tata Teleservices Maharashtra","sector":"Telecom","index":"NIFTY Microcap"},
    {"symbol":"GTLINFRA.NS","name":"GTL Infrastructure","sector":"Telecom","index":"NIFTY Microcap"},
    {"symbol":"TEJASNET.NS","name":"Tejas Networks","sector":"Telecom","index":"NIFTY Microcap"},
    {"symbol":"JYOTICNC.NS","name":"Jyoti CNC Automation","sector":"Capital Goods","index":"NIFTY Microcap"},
    {"symbol":"HEG.NS","name":"HEG Limited","sector":"Capital Goods","index":"NIFTY Microcap"},
    {"symbol":"BHEL.NS","name":"Bharat Heavy Electricals","sector":"Capital Goods","index":"NIFTY Microcap"},
    {"symbol":"BHARAT.NS","name":"Bharat Forge","sector":"Capital Goods","index":"NIFTY Microcap"},
    {"symbol":"ISGEC.NS","name":"Isgec Heavy Engineering","sector":"Capital Goods","index":"NIFTY Microcap"},
    {"symbol":"VOLTAMP.NS","name":"Voltamp Transformers","sector":"Capital Goods","index":"NIFTY Microcap"},
    {"symbol":"TDPOWERSYS.NS","name":"TD Power Systems","sector":"Capital Goods","index":"NIFTY Microcap"},
    {"symbol":"KSOLVES.NS","name":"Ksolves India","sector":"IT","index":"NIFTY Microcap"},
    {"symbol":"HAPPYFORGE.NS","name":"Happy Forgings","sector":"Capital Goods","index":"NIFTY Microcap"},
    {"symbol":"RAILSYS.NS","name":"RITES Limited","sector":"Infra","index":"NIFTY Microcap"},
    {"symbol":"RITES.NS","name":"RITES Limited","sector":"Infra","index":"NIFTY Microcap"},
    {"symbol":"NBCC.NS","name":"NBCC India","sector":"Infra","index":"NIFTY Microcap"},
    {"symbol":"HUDCO.NS","name":"Housing & Urban Development","sector":"Infra","index":"NIFTY Microcap"},
    {"symbol":"NHAI.NS","name":"National Highways Infra","sector":"Infra","index":"NIFTY Microcap"},
    {"symbol":"IRCON.NS","name":"IRCON International","sector":"Infra","index":"NIFTY Microcap"},
    {"symbol":"VGUARD.NS","name":"V-Guard Industries","sector":"Consumer Durables","index":"NIFTY Microcap"},
    {"symbol":"ORIENTELEC.NS","name":"Orient Electric","sector":"Consumer Durables","index":"NIFTY Microcap"},
    {"symbol":"BAJAJELEC.NS","name":"Bajaj Electricals","sector":"Consumer Durables","index":"NIFTY Microcap"},
    {"symbol":"SYRMA.NS","name":"Syrma SGS Technology","sector":"Electronics","index":"NIFTY Microcap"},
    {"symbol":"IDEALSOL.NS","name":"Ideal Integral Solutions","sector":"IT","index":"NIFTY Microcap"},
    {"symbol":"NEWGEN.NS","name":"Newgen Software","sector":"IT","index":"NIFTY Microcap"},
    {"symbol":"SONACOMS.NS","name":"Sona BLW Precision","sector":"Auto Ancillary","index":"NIFTY Microcap"},
    {"symbol":"SAMHI.NS","name":"Samhi Hotels","sector":"Hospitality","index":"NIFTY Microcap"},
    {"symbol":"SAPPHIRE.NS","name":"Sapphire Foods","sector":"QSR","index":"NIFTY Microcap"},
    {"symbol":"BARBEQUE.NS","name":"Barbeque Nation","sector":"QSR","index":"NIFTY Microcap"},
    {"symbol":"SPECIALITY.NS","name":"Speciality Restaurants","sector":"QSR","index":"NIFTY Microcap"},
    {"symbol":"TASTYBITE.NS","name":"Tasty Bite Eatables","sector":"FMCG","index":"NIFTY Microcap"},
    {"symbol":"AVANTIFEED.NS","name":"Avanti Feeds","sector":"Aquaculture","index":"NIFTY Microcap"},
    {"symbol":"WATERBASE.NS","name":"Waterbase","sector":"Aquaculture","index":"NIFTY Microcap"},
    {"symbol":"APLT.NS","name":"Applied DNA Sciences","sector":"Biotech","index":"NIFTY Microcap"},
    {"symbol":"SEQUENT.NS","name":"Sequent Scientific","sector":"Pharma","index":"NIFTY Microcap"},
    {"symbol":"STRIDES.NS","name":"Strides Pharma","sector":"Pharma","index":"NIFTY Microcap"},
    {"symbol":"SOLARA.NS","name":"Solara Active Pharma","sector":"Pharma","index":"NIFTY Microcap"},
    {"symbol":"GLAND.NS","name":"Gland Pharma","sector":"Pharma","index":"NIFTY Microcap"},
    {"symbol":"ERIS.NS","name":"Eris Lifesciences","sector":"Pharma","index":"NIFTY Microcap"},
    {"symbol":"JB.NS","name":"JB Chemicals & Pharma","sector":"Pharma","index":"NIFTY Microcap"},
    {"symbol":"WINDLAS.NS","name":"Windlas Biotech","sector":"Pharma","index":"NIFTY Microcap"},
    {"symbol":"PIRAMALENT.NS","name":"Piramal Enterprises","sector":"Pharma","index":"NIFTY Microcap"},
    {"symbol":"SANOFI.NS","name":"Sanofi India","sector":"Pharma","index":"NIFTY Microcap"},
    {"symbol":"PFIZER.NS","name":"Pfizer India","sector":"Pharma","index":"NIFTY Microcap"},
    {"symbol":"ABOTT.NS","name":"Abbott India","sector":"Pharma","index":"NIFTY Microcap"},
    {"symbol":"GLAXO.NS","name":"GSK Pharmaceuticals India","sector":"Pharma","index":"NIFTY Microcap"},
    {"symbol":"NOVARTIS.NS","name":"Novartis India","sector":"Pharma","index":"NIFTY Microcap"},
    {"symbol":"ASTRAZEN.NS","name":"AstraZeneca Pharma India","sector":"Pharma","index":"NIFTY Microcap"},
    {"symbol":"RPGLIFE.NS","name":"RPG Life Sciences","sector":"Pharma","index":"NIFTY Microcap"},
    {"symbol":"GHCL.NS","name":"GHCL Limited","sector":"Chemicals","index":"NIFTY Microcap"},
    {"symbol":"NACLIND.NS","name":"NACL Industries","sector":"Agrochemicals","index":"NIFTY Microcap"},
    {"symbol":"DHANUKA.NS","name":"Dhanuka Agritech","sector":"Agrochemicals","index":"NIFTY Microcap"},
    {"symbol":"RALLIS.NS","name":"Rallis India","sector":"Agrochemicals","index":"NIFTY Microcap"},
    {"symbol":"PI.NS","name":"PI Industries","sector":"Agrochemicals","index":"NIFTY Microcap"},
    {"symbol":"SUMICHEM.NS","name":"Sumitomo Chemical India","sector":"Agrochemicals","index":"NIFTY Microcap"},
    {"symbol":"BAYERCROP.NS","name":"Bayer Cropscience","sector":"Agrochemicals","index":"NIFTY Microcap"},
    {"symbol":"INSECTICID.NS","name":"Insecticides India","sector":"Agrochemicals","index":"NIFTY Microcap"},
    {"symbol":"GODREJAGRO.NS","name":"Godrej Agrovet","sector":"Agrochemicals","index":"NIFTY Microcap"},
    {"symbol":"ZUARI.NS","name":"Zuari Agro Chemicals","sector":"Fertilisers","index":"NIFTY Microcap"},
    {"symbol":"DEEPAKFERT.NS","name":"Deepak Fertilisers","sector":"Fertilisers","index":"NIFTY Microcap"},
    {"symbol":"GSFC.NS","name":"Gujarat State Fertilizers","sector":"Fertilisers","index":"NIFTY Microcap"},
    {"symbol":"NFL.NS","name":"National Fertilizers","sector":"Fertilisers","index":"NIFTY Microcap"},
    {"symbol":"RCF.NS","name":"Rashtriya Chemicals","sector":"Fertilisers","index":"NIFTY Microcap"},
    {"symbol":"FACT.NS","name":"Fertilisers & Chemicals Travancore","sector":"Fertilisers","index":"NIFTY Microcap"},
    {"symbol":"TATAELXSI.NS","name":"Tata Elxsi","sector":"IT","index":"NIFTY Microcap"},
    {"symbol":"CYIENT.NS","name":"Cyient Limited","sector":"IT","index":"NIFTY Microcap"},
    {"symbol":"NIITTECH.NS","name":"NIIT Learning Systems","sector":"IT","index":"NIFTY Microcap"},
    {"symbol":"RAMSYS.NS","name":"Ram Systems","sector":"IT","index":"NIFTY Microcap"},
    {"symbol":"INFOBEAN.NS","name":"InfoBeans Technologies","sector":"IT","index":"NIFTY Microcap"},
    {"symbol":"NUCLEUS.NS","name":"Nucleus Software","sector":"IT","index":"NIFTY Microcap"},
    {"symbol":"DATAMATICS.NS","name":"Datamatics Global","sector":"IT","index":"NIFTY Microcap"},
    {"symbol":"INTELLECT.NS","name":"Intellect Design Arena","sector":"IT","index":"NIFTY Microcap"},
    {"symbol":"MPHASIS.NS","name":"Mphasis","sector":"IT","index":"NIFTY Microcap"},
    {"symbol":"HEXAWARE.NS","name":"Hexaware Technologies","sector":"IT","index":"NIFTY Microcap"},
    {"symbol":"SONATA.NS","name":"Sonata Software","sector":"IT","index":"NIFTY Microcap"},
    {"symbol":"NETSOL.NS","name":"Net Solution Technologies","sector":"IT","index":"NIFTY Microcap"},
    {"symbol":"TATATECH.NS","name":"Tata Technologies","sector":"IT","index":"NIFTY Microcap"},
    {"symbol":"LATENTVIEW.NS","name":"Latent View Analytics","sector":"IT","index":"NIFTY Microcap"},
    {"symbol":"HAPPSTMNDS.NS","name":"Happiest Minds","sector":"IT","index":"NIFTY Microcap"},
    {"symbol":"HBLPOWER.NS","name":"HBL Power Systems","sector":"Capital Goods","index":"NIFTY Microcap"},
    {"symbol":"INOXWIND.NS","name":"Inox Wind","sector":"Power","index":"NIFTY Microcap"},
    {"symbol":"WEBSOL.NS","name":"Websol Energy System","sector":"Power","index":"NIFTY Microcap"},
    {"symbol":"WAAREEENER.NS","name":"Waaree Energies","sector":"Power","index":"NIFTY Microcap"},
    {"symbol":"PREMIERENE.NS","name":"Premier Energies","sector":"Power","index":"NIFTY Microcap"},
    {"symbol":"GOKALDAS.NS","name":"Gokaldas Exports","sector":"Textiles","index":"NIFTY Microcap"},
    {"symbol":"NANDAN.NS","name":"Nandan Denim","sector":"Textiles","index":"NIFTY Microcap"},
    {"symbol":"INDSWFTLAB.NS","name":"Ind-Swift Laboratories","sector":"Pharma","index":"NIFTY Microcap"},
    {"symbol":"PANACEA.NS","name":"Panacea Biotec","sector":"Pharma","index":"NIFTY Microcap"},
    {"symbol":"MARKSANS.NS","name":"Marksans Pharma","sector":"Pharma","index":"NIFTY Microcap"},
    {"symbol":"MOREPEN.NS","name":"Morepen Laboratories","sector":"Pharma","index":"NIFTY Microcap"},
    {"symbol":"UNICHEM.NS","name":"Unichem Laboratories","sector":"Pharma","index":"NIFTY Microcap"},
    {"symbol":"SUVEN.NS","name":"Suven Pharmaceuticals","sector":"Pharma","index":"NIFTY Microcap"},
    {"symbol":"PRITIKAUTO.NS","name":"Pritika Auto Industries","sector":"Auto Ancillary","index":"NIFTY Microcap"},
    {"symbol":"CRAFTEDGE.NS","name":"Craftsman Automation","sector":"Auto Ancillary","index":"NIFTY Microcap"},
    {"symbol":"MAXVIL.NS","name":"Max Ventures","sector":"Real Estate","index":"NIFTY Microcap"},
    {"symbol":"NESCO.NS","name":"NESCO Limited","sector":"Real Estate","index":"NIFTY Microcap"},
    {"symbol":"SUNTECK.NS","name":"Sunteck Realty","sector":"Real Estate","index":"NIFTY Microcap"},
    {"symbol":"MAHLIFE.NS","name":"Mahindra Lifespace","sector":"Real Estate","index":"NIFTY Microcap"},
    {"symbol":"KOLTEPATIL.NS","name":"Kolte-Patil Developers","sector":"Real Estate","index":"NIFTY Microcap"},
    {"symbol":"PURAVANKARA.NS","name":"Puravankara","sector":"Real Estate","index":"NIFTY Microcap"},
    {"symbol":"ANANTRAJ.NS","name":"Anant Raj","sector":"Real Estate","index":"NIFTY Microcap"},
    {"symbol":"ELDEHSG.NS","name":"Eldeco Housing","sector":"Real Estate","index":"NIFTY Microcap"},
    {"symbol":"ARVINDSMRT.NS","name":"Arvind SmartSpaces","sector":"Real Estate","index":"NIFTY Microcap"},
    {"symbol":"INDIAMART.NS","name":"IndiaMART InterMESH","sector":"Internet","index":"NIFTY Microcap"},
    {"symbol":"JUSTDIAL.NS","name":"Just Dial","sector":"Internet","index":"NIFTY Microcap"},
    {"symbol":"AFFLE.NS","name":"Affle India","sector":"Internet","index":"NIFTY Microcap"},
    {"symbol":"NAZARA.NS","name":"Nazara Technologies","sector":"Internet","index":"NIFTY Microcap"},
    {"symbol":"DELTACORP.NS","name":"Delta Corp","sector":"Gaming","index":"NIFTY Microcap"},
    {"symbol":"ONDC.NS","name":"One Digital Entertainment","sector":"Media","index":"NIFTY Microcap"},
    {"symbol":"SAREGAMA.NS","name":"Saregama India","sector":"Media","index":"NIFTY Microcap"},
    {"symbol":"TIPS.NS","name":"Tips Music","sector":"Media","index":"NIFTY Microcap"},
    {"symbol":"NDTV.NS","name":"NDTV","sector":"Media","index":"NIFTY Microcap"},
    {"symbol":"SUNCLAYLTD.NS","name":"Sun Clay","sector":"Media","index":"NIFTY Microcap"},
    {"symbol":"HATHWAY.NS","name":"Hathway Cable","sector":"Media","index":"NIFTY Microcap"},
    {"symbol":"SIEVERT.NS","name":"Sieverth Industries","sector":"Diversified","index":"NIFTY Microcap"},
    {"symbol":"EDELWEISS.NS","name":"Edelweiss Financial","sector":"NBFC","index":"NIFTY Microcap"},
    {"symbol":"JM.NS","name":"JM Financial","sector":"NBFC","index":"NIFTY Microcap"},
    {"symbol":"MOTILALOS.NS","name":"Motilal Oswal Financial","sector":"Broking","index":"NIFTY Microcap"},
    {"symbol":"GEOJITFSL.NS","name":"Geojit Financial Services","sector":"Broking","index":"NIFTY Microcap"},
    {"symbol":"CHOICEIN.NS","name":"Choice International","sector":"Broking","index":"NIFTY Microcap"},
    {"symbol":"SMIFS.NS","name":"SMIFS Securities","sector":"Broking","index":"NIFTY Microcap"},
    {"symbol":"NUVAMA.NS","name":"Nuvama Wealth Management","sector":"Wealth Mgmt","index":"NIFTY Microcap"},
    {"symbol":"UTIAMC.NS","name":"UTI Asset Management","sector":"AMC","index":"NIFTY Microcap"},
    {"symbol":"SUNDARAM.NS","name":"Sundaram Finance","sector":"NBFC","index":"NIFTY Microcap"},
    {"symbol":"CAPLIPOINT.NS","name":"Caplin Point Laboratories","sector":"Pharma","index":"NIFTY Microcap"},
    {"symbol":"VINATIORGA.NS","name":"Vinati Organics","sector":"Chemicals","index":"NIFTY Microcap"},
    {"symbol":"GALLANTT.NS","name":"Gallantt Metal","sector":"Metals","index":"NIFTY Microcap"},
    {"symbol":"NCLIND.NS","name":"NCL Industries","sector":"Cement","index":"NIFTY Microcap"},
    {"symbol":"MANGCMTML.NS","name":"Mangalam Cement","sector":"Cement","index":"NIFTY Microcap"},
    {"symbol":"KAKATCEM.NS","name":"Kakatiya Cement","sector":"Cement","index":"NIFTY Microcap"},
    {"symbol":"HEIDELBERG.NS","name":"HeidelbergCement India","sector":"Cement","index":"NIFTY Microcap"},
    {"symbol":"NUVOCO.NS","name":"Nuvoco Vistas Corp","sector":"Cement","index":"NIFTY Microcap"},
    {"symbol":"ORIENTCEM.NS","name":"Orient Cement","sector":"Cement","index":"NIFTY Microcap"},
    {"symbol":"SNOWMAN.NS","name":"Snowman Logistics","sector":"Logistics","index":"NIFTY Microcap"},
    {"symbol":"ALLCARGO.NS","name":"Allcargo Logistics","sector":"Logistics","index":"NIFTY Microcap"},
    {"symbol":"TVSSCS.NS","name":"TVS Supply Chain Solutions","sector":"Logistics","index":"NIFTY Microcap"},
    {"symbol":"AEGISLOG.NS","name":"Aegis Logistics","sector":"Logistics","index":"NIFTY Microcap"},
    {"symbol":"INFOSONICS.NS","name":"Infosonics Corporation","sector":"Electronics","index":"NIFTY Microcap"},
    {"symbol":"OPTIEMUS.NS","name":"Optiemus Infracom","sector":"Electronics","index":"NIFTY Microcap"},
    {"symbol":"PGEL.NS","name":"PG Electroplast","sector":"Electronics","index":"NIFTY Microcap"},
    {"symbol":"VMRDA.NS","name":"V2 Retail","sector":"Retail","index":"NIFTY Microcap"},
    {"symbol":"SHOPERSTOP.NS","name":"Shopper's Stop","sector":"Retail","index":"NIFTY Microcap"},
    {"symbol":"TRENDSUTRA.NS","name":"Trend Sutra","sector":"Retail","index":"NIFTY Microcap"},
    {"symbol":"CAMPUS.NS","name":"Campus Activewear","sector":"Consumer","index":"NIFTY Microcap"},
    {"symbol":"METRO.NS","name":"Metro Brands","sector":"Consumer","index":"NIFTY Microcap"},
    {"symbol":"KHADIM.NS","name":"Khadim India","sector":"Consumer","index":"NIFTY Microcap"},
    {"symbol":"MHRIL.NS","name":"Mahindra Holidays","sector":"Hospitality","index":"NIFTY Microcap"},
    {"symbol":"WONDERLA.NS","name":"Wonderla Holidays","sector":"Hospitality","index":"NIFTY Microcap"},
    {"symbol":"THOMASCOOK.NS","name":"Thomas Cook India","sector":"Travel","index":"NIFTY Microcap"},
    {"symbol":"MAKEIND.NS","name":"Make My India","sector":"Travel","index":"NIFTY Microcap"},
    {"symbol":"YATHARTH.NS","name":"Yatharth Hospital","sector":"Healthcare","index":"NIFTY Microcap"},
    {"symbol":"KIMS.NS","name":"Krishna Institute Medical Sci","sector":"Healthcare","index":"NIFTY Microcap"},
    {"symbol":"RAINBOW.NS","name":"Rainbow Children's Medicare","sector":"Healthcare","index":"NIFTY Microcap"},
    {"symbol":"SAGILITY.NS","name":"Sagility India","sector":"Healthcare IT","index":"NIFTY Microcap"},
    {"symbol":"KRSNAA.NS","name":"Krsnaa Diagnostics","sector":"Healthcare","index":"NIFTY Microcap"},
    {"symbol":"VIJAYA.NS","name":"Vijaya Diagnostic Centre","sector":"Healthcare","index":"NIFTY Microcap"},
    {"symbol":"CARERATINGS.NS","name":"CARE Ratings","sector":"Financial Services","index":"NIFTY Microcap"},
    {"symbol":"ICRA.NS","name":"ICRA Limited","sector":"Financial Services","index":"NIFTY Microcap"},
    {"symbol":"CRISIL.NS","name":"CRISIL","sector":"Financial Services","index":"NIFTY Microcap"},
    {"symbol":"ACCELYA.NS","name":"Accelya Solutions","sector":"IT","index":"NIFTY Microcap"},
    {"symbol":"ZENSAR.NS","name":"Zensar Technologies","sector":"IT","index":"NIFTY Microcap"},
    {"symbol":"NIIT.NS","name":"NIIT Limited","sector":"IT","index":"NIFTY Microcap"},
    {"symbol":"ECLERX.NS","name":"eClerx Services","sector":"IT","index":"NIFTY Microcap"},
    {"symbol":"RATEGAIN.NS","name":"RateGain Travel Tech","sector":"IT","index":"NIFTY Microcap"},
    {"symbol":"QUESS.NS","name":"Quess Corp","sector":"Staffing","index":"NIFTY Microcap"},
    {"symbol":"TEAMLEASE.NS","name":"TeamLease Services","sector":"Staffing","index":"NIFTY Microcap"},
    {"symbol":"XPROINDIA.NS","name":"Xpro India","sector":"Chemicals","index":"NIFTY Microcap"},
    {"symbol":"ASAHIINDIA.NS","name":"Asahi India Glass","sector":"Capital Goods","index":"NIFTY Microcap"},
    {"symbol":"HLEGLAZING.NS","name":"HLE Glascoat","sector":"Capital Goods","index":"NIFTY Microcap"},
    {"symbol":"SUPRAJIT.NS","name":"Suprajit Engineering","sector":"Auto Ancillary","index":"NIFTY Microcap"},
    {"symbol":"GUFICBIO.NS","name":"Gufic Biosciences","sector":"Pharma","index":"NIFTY Microcap"},
    {"symbol":"CIGNITITEC.NS","name":"Cigniti Technologies","sector":"IT","index":"NIFTY Microcap"},
    {"symbol":"SAKUMA.NS","name":"Sakuma Exports","sector":"Agri","index":"NIFTY Microcap"},
    {"symbol":"SAFARI.NS","name":"Safari Industries","sector":"Consumer","index":"NIFTY Microcap"},
    {"symbol":"EQUITAS.NS","name":"Equitas Holdings","sector":"Banking","index":"NIFTY Microcap"},
    {"symbol":"FUSION.NS","name":"Fusion Micro Finance","sector":"NBFC","index":"NIFTY Microcap"},
    {"symbol":"AROHAN.NS","name":"Arohan Financial Services","sector":"NBFC","index":"NIFTY Microcap"},
    {"symbol":"KFINTECH.NS","name":"KFin Technologies","sector":"Financial Services","index":"NIFTY Microcap"},
    {"symbol":"SBFC.NS","name":"SBFC Finance","sector":"NBFC","index":"NIFTY Microcap"},
    {"symbol":"VIRINCHI.NS","name":"Virinchi Limited","sector":"IT","index":"NIFTY Microcap"},
    {"symbol":"SUVENPHAR.NS","name":"Suven Life Sciences","sector":"Pharma","index":"NIFTY Microcap"},
    {"symbol":"MANKIND.NS","name":"Mankind Pharma","sector":"Pharma","index":"NIFTY Microcap"},
    {"symbol":"RPSGVENT.NS","name":"RPSG Ventures","sector":"Diversified","index":"NIFTY Microcap"},
    {"symbol":"GOCOLORS.NS","name":"Go Fashion (Go Colors)","sector":"Retail","index":"NIFTY Microcap"},
    {"symbol":"VEDANT.NS","name":"Vedant Fashions (Manyavar)","sector":"Retail","index":"NIFTY Microcap"},
    {"symbol":"NYKAA.NS","name":"Nykaa","sector":"E-Commerce","index":"NIFTY Microcap"},
]

# Deduplicate by symbol
seen = set()
UNIQUE_STOCKS = []
for s in NSE_STOCKS:
    if s["symbol"] not in seen:
        seen.add(s["symbol"])
        UNIQUE_STOCKS.append(s)
NSE_STOCKS = UNIQUE_STOCKS

ALL_NSE_SYMBOLS = [s["symbol"] for s in NSE_STOCKS]
NSE_STOCK_MAP   = {s["symbol"]: s for s in NSE_STOCKS}
DEFAULT_SYMBOLS = [s["symbol"] for s in NSE_STOCKS if s["index"] == "NIFTY 50"]
SECTORS  = sorted(set(s["sector"] for s in NSE_STOCKS))
INDICES  = ["NIFTY 50", "NIFTY Next 50", "NIFTY Midcap", "NIFTY Smallcap", "NIFTY Microcap", "All"]
